home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns=[
    path('register/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name="logout"),
    path('', views.home, name="index"),
]

khachsanvt/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('gallery/', include('quanlyphong.urls')),
    path('thongtinkh/', include('quanlykhachhang.urls')),
    path('datphong/', include('phieudatphong.urls')),
    path('', include('home.urls')),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phieudatphong/models.py
from django.db import models
from quanlykhachhang.models import Khachhang
from quanlyphong.models import Phong
# Create your models here.

class PhieuDatPhong(models.Model):
    MaKH=models.ForeignKey(Khachhang,on_delete=models.CASCADE)
    MaPhong=models.ForeignKey(Phong,on_delete=models.CASCADE )
    NgayNhan=models.DateField(null=False)
    NgayTra=models.DateField(null=False)

    def __str__ (self):
        return str(self.id)

quanlynhanvien/models.py
from django.db import models

# Create your models here.
class Nhanvien(models.Model):
    MaNV=models.CharField(primary_key=True, max_length=5)
    TenNV=models.CharField(max_length=50, null=False)
    Cccd=models.CharField(max_length=12, null=False, unique=True)
    Mst=models.CharField(max_length=10, null=False, unique=True)
    email=models.EmailField(null=False, unique=True)
    Sdt=models.CharField(max_length=10,null=False, unique=True)
    DiaChi=models.CharField(max_length=120,null=False)

    def __str__(self):
        return self.MaNV

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from quanlyphong.models import Phong
import re

class CustomPasswordInput(forms.PasswordInput):
    def __init__(self, *args, **kwargs):
        attrs = kwargs.get('attrs', {})
        attrs['class'] = 'form-control'
        kwargs['attrs'] = attrs
        super().__init__(*args, **kwargs)

class RegistrationForm(forms.Form):
    username=forms.CharField(label="Tài khoản", max_length=30,widget=forms.TextInput(attrs={'class': 'form-control'}))
    firstname=forms.CharField(label="First name ", max_length=50,widget=forms.TextInput(attrs={'class': 'form-control'}))
    lastname=forms.CharField(label="Last name ", max_length=50,widget=forms.TextInput(attrs={'class': 'form-control'}))
    email=forms.EmailField(label="Email",widget=forms.TextInput(attrs={'class': 'form-control'}))
    password=forms.CharField(label="Mật khẩu", widget=CustomPasswordInput())
    password2=forms.CharField(label="Nhập lại mật khẩu", widget=CustomPasswordInput())
    
    def clean(self):
        cleaned_data = super().clean() 
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')

        if password!=password2:
            raise forms.ValidationError("Mật khẩu không hợp lệ")
        return cleaned_data
    
    def clean_username(self):
        username=self.cleaned_data['username']

        if not re.search(r'^\w+$', username):
            raise forms.ValidationError("Tên tài khoản có ký tự đặc biệt")
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản đã tồn tại")
    
    def save(self):
        User.objects.create_user(username=self.cleaned_data['username'],first_name=self.cleaned_data['firstname'],last_name=self.cleaned_data['lastname'],
                                 email= self.cleaned_data['email'], password=self.cleaned_data['password2'])
        
class LoadPhong(forms.Form):
    class Meta():
        model= Phong()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
   <head>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>keto</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      <!-- bootstrap css -->
      
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
      <!-- style css -->
      <link rel="stylesheet" href="{% static 'css/style.css'%}">
      <link rel="stylesheet" href="{% static 'css/gioithieu.css'%}">
      <!-- Responsive-->
      <link rel="stylesheet" href="{% static 'css/responsive.css'%}">
      <!-- fevicon -->
      <!-- <link rel="icon" href="{% static 'images/fevicon.png" type="image/gif" /> -->
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/jquery.mCustomScrollbar.min.css'%}">
      <!-- Tweaks for older IEs-->
      <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
   </head>
   <!-- body -->
   <body class="main-layout">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="{% static 'images/loading.gif'%}" alt="#"/></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container">
               <div class="row">
                  <div class="col-xl-2 col-lg-2 col-md-2 col-sm-2 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="index.html"><img src="{% static 'images/logo.png'%}" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-10 col-lg-10 col-md-10 col-sm-10">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                            {% if user.username %}
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'index' %}" style="margin: 0 10px;">Trang chủ</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{%url 'phieudat'%}" style="margin: 0 10px;">Đặt phòng</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'gallery' %}" style="margin: 0 10px;">Gallery</a>
                              </li>
                             <li class="nav-item">
                                <!-- <a class="nav-link" href="" style="margin: 0 10px;">Thông tin khách hàng</a> -->
                             </li>
                             <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                 Xin chào {{user.last_name}}
                              </a>
                              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'thongtinkh'%}">Thông tin khách hàng</a>
                                <a class="dropdown-item" href="{% url 'logout' %}">Đăng xuất</a>
                                <!-- <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a> -->
                              </div>
                            </li>
                              {% else %}
                              <li class="nav-item">
                                 <a href="#" class="nav-link" style="margin: 0 10px;">Trang chủ</a>
                              </li>
                              <li class="nav-item">
                                 <a href="{% url 'login' %}" class="nav-link"style="margin: 0 10px;">Đăng nhập</a>
                              </li>
                              <li class="nav-item">
                                 <a href="{% url 'register' %}" class="nav-link" style="margin: 0 10px;">Đăng ký</a>
                              </li>
                              {% endif%}
                              <form class="form-inline" style="margin: 0 0 30px 0;">
                                    <input class="form-control mr-sm-1" type="search" placeholder="Search" aria-label="Search">
                                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                              </form>
                              
                           </ul>
                        </div>
                     </nav>
                  </div>
               </div>
            </div>
         </div>
      </header>
      <!-- end header inner -->
      <!-- end header -->
      {% block content %}
      {%endblock%}
      <!--  footer -->
      <footer>
         <div class="footer">
            <div class="container">
               <div class="row">
                  <div class=" col-md-4">
                     <h3>Contact Us</h3>
                     <ul class="conta">
                        <li><i class="fa fa-map-marker" aria-hidden="true"></i> Address</li>
                        <li><i class="fa fa-mobile" aria-hidden="true"></i> +01 1234569540</li>
                        <li> <i class="fa fa-envelope" aria-hidden="true"></i><a href="#"> demo@gmail.com</a></li>
                     </ul>
                  </div>
                  <div class="col-md-4">
                     <h3>Menu Link</h3>
                     <ul class="link_menu">
                        <li class=""><a href="{% url 'index' %}">Trang chủ</a></li>
                        <li><a href="{%url 'phieudat'%}"> Đặt phòng</a></li>
                        <li><a href="{% url 'gallery' %}">Gallery</a></li>
                        <li><a href="">Xin chào {{user.last_name}}</a></li>
                     </ul>
                  </div>
                  <div class="col-md-4">
                     <h3>News letter</h3>
                     <form class="bottom_form">
                        <input class="enter" placeholder="Enter your email" type="text" name="Enter your email">
                        <button class="sub_btn">subscribe</button>
                     </form>
                     <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="copyright">
               <div class="container">
                  <div class="row">
                     <div class="col-md-10 offset-md-1">
                        
                        <p>
                        © 2019 All Rights Reserved. Design by <a href="https://html.design/"> Free Html Templates</a>
                        <br><br>
                        Distributed by <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
                        </p>

                     </div>
                  </div>
               </div>
            </div>
         </div>
      </footer>
      <!-- end footer -->
      <!-- Javascript files-->
      <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
      <script src="{% static 'js/jquery.min.js'%}"></script>
      <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
      <script src="{% static 'js/jquery-3.0.0.min.js'%}"></script>
      <!-- sidebar -->
      <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js'%}"></script>
      <script src="{% static 'js/custom.js'%}"></script>
      <script>
         $(document).ready(function() {
             // Thêm class vào trường username và password sau khi trang đã tải
             $('#id_username').addClass('form-control');
             $('#id_password').addClass('form-control');
             $('#id_Cccd').addClass('form-control');
             $('#id_TenKhachHang').addClass('form-control');
             $('#id_email').addClass('form-control');
             $('#id_Sdt').addClass('form-control');
             $('#id_DiaChi').addClass('form-control');
             $('#id_MaKH').addClass('form-control');
             $('#id_MaPhong').addClass('form-control');
             $('#id_NgayNhan').addClass('form-control');
             $('#id_NgayTra').addClass('form-control');
         });
         </script>
   </body>
</html>

templates/datphong.html
{% extends "base.html" %}
{% block content %}

    <div class="back_re">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title">
                        <h2>Đặt phòng</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="vh-100 bg-image"
      style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp'); margin: 10px 0;">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px;">
                            <div class="card-body p-5">
                                <form action="." method="POST" class="mx-1 mx-md-4">
                                    {% csrf_token %}
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example1cg">Mã khách hàng</label>
                                        {{ form.MaKH }}
                                    </div>

                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example4cg">Mã phòng</label>
                                        {{ form.MaPhong }}
                                    </div>
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example4cg">Ngày nhận</label>
                                        {{ form.NgayNhan }}
                                    </div>
                                    <div class="form-outline mb-4">
                                        <label class="form-label" for="form3Example4cg">Ngày trả</label>
                                        {{ form.NgayTra }}
                                    </div>

                                    <input type="hidden" name="next" value="/">
                                    <div class="d-flex justify-content-center">
                                        <input type="submit"
                                               class="btn btn-success btn-block btn-lg gradient-custom-4 text-body"
                                               value="Đặt phòng">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/dsphieu.html
{%extends "base.html"%}
{%block content%}
<div class="back_re">
    <div class="container">
       <div class="row">
          <div class="col-md-12">
             <div class="title">
               <h2>Phiếu đặt phòng</h2>
             </div>
          </div>
       </div>
    </div>
</div>
    {% if phieu %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Mã Khách Hàng</th>
                    <th scope="col">Mã Phòng</th>
                    <th scope="col">Ngày Nhận</th>
                    <th scope="col">Ngày Trả</th>
                </tr>
            </thead>
            <tbody>
                {% for phieu_dat in phieu %}
                    <tr>
                        <td>{{ phieu_dat.MaKH.Cccd }}</td>
                        <td>{{ phieu_dat.MaPhong}}</td>
                        <td>{{ phieu_dat.NgayNhan }}</td>
                        <td>{{ phieu_dat.NgayTra }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Không có phiếu đặt nào.</p>
    {% endif %}
{%endblock%}

templates/gallery.html
{%extends "base.html"%}
{%block content%}
<div class="back_re">
    <div class="container">
       <div class="row">
          <div class="col-md-12">
             <div class="title">
               <h2>gallery</h2>
             </div>
          </div>
       </div>
    </div>
</div>
 <!-- gallery -->
<div  class="gallery">
   <div class="container">
      <form action="" method="post">
         {% csrf_token %}
         <div class="row">
            {% for anh in fm %}
            <div class="col-md-3 col-sm-6">
               <div class="gallery_img">
                  <figure><img src="../static/images/{{anh.Anhphong}}" alt="#"/></figure>
               </div>
            </div>
            {%endfor%}
         </div>
      </form>
   </div>
</div>
 <!-- end gallery -->
{%endblock%}

templates/index.html
{%extends "base.html"%}
{%block content%}
      <!-- banner -->
      <section class="banner_main">
         <div id="myCarousel" class="carousel slide banner" data-ride="carousel">
            <ol class="carousel-indicators">
               <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
               <li data-target="#myCarousel" data-slide-to="1"></li>
               <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
               <div class="carousel-item active">
                  <img class="first-slide" src="../static/images/banner1.jpg" alt="First slide">
                  <div class="container">
                  </div>
               </div>
               <div class="carousel-item">
                  <img class="second-slide" src="../static/images/banner2.jpg" alt="Second slide">
               </div>
               <div class="carousel-item">
                  <img class="third-slide" src="../static/images/banner3.jpg" alt="Third slide">
               </div>
            </div>
            <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
         </div>
      </section>
      <!-- end banner -->
      <!-- about -->
      <div class="about">
         <div class="container-fluid">
            <div class="row">
               <div class="col-md-5">
                  <div class="titlepage">
                     <h2>About Us</h2>
                     <p>The passage experienced a surge in popularity during the 1960s when Letraset used it on their dry-transfer sheets, and again during the 90s as desktop publishers bundled the text with their software. Today it's seen all around the web; on templates, websites, and stock designs. Use our generator to get your own, or read on for the authoritative history of lorem ipsum. </p>
                     <a class="read_more" href="Javascript:void(0)"> Read More</a>
                  </div>
               </div>
               <div class="col-md-7">
                  <div class="about_img">
                     <figure><img src="../static/images/about.png" alt="#"/></figure>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end about -->
      <!-- our_room -->
      <form action="" method="post">
         {% csrf_token %}
         
         <div  class="our_room">
            <div class="container">
               <div class="row">
                  <div class="col-md-12">
                     <div class="titlepage">
                        <h2>Our Room</h2>
                        <p>Lorem Ipsum available, but the majority have suffered </p>
                     </div>
                  </div>
               </div>
               <div class="row">
                  
                  {% for phong in phong_trong %}
                     <div class="col-md-4 col-sm-6">
                        <div id="serv_hover"  class="room">
                           <a href="{% url 'detail'%}?id={{phong.Maphong}}">
                              <div class="room_img">
                                 <figure><img src="../static/images/{{phong.Anhphong}}" alt="#"/></figure>
                              </div>
                              <div class="bed_room">
                                 <h3>{{phong.Loaiphong}}</h3>
                                 <p>{{phong.Giaphong}} VNĐ</p>
                              </div>
                           </a>
                        </div>
                     </div>
                  {%endfor%}
               </div>
            </div>
         </div>
         <!-- end our_room -->
         </form>
      <!-- blog -->
      <div  class="blog">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Blog</h2>
                     <p>Lorem Ipsum available, but the majority have suffered </p>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-4">
                  <div class="blog_box">
                     <div class="blog_img">
                        <figure><img src="../static/images/blog1.jpg" alt="#"/></figure>
                     </div>
                     <div class="blog_room">
                        <h3>Bed Room</h3>
                        <span>The standard chunk </span>
                        <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generatorsIf you are   </p>
                     </div>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="blog_box">
                     <div class="blog_img">
                        <figure><img src="../static/images/blog2.jpg" alt="#"/></figure>
                     </div>
                     <div class="blog_room">
                        <h3>Bed Room</h3>
                        <span>The standard chunk </span>
                        <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generatorsIf you are   </p>
                     </div>
                  </div>
               </div>
               <div class="col-md-4">
                  <div class="blog_box">
                     <div class="blog_img">
                        <figure><img src="../static/images/blog3.jpg" alt="#"/></figure>
                     </div>
                     <div class="blog_room">
                        <h3>Bed Room</h3>
                        <span>The standard chunk </span>
                        <p>If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generatorsIf you are   </p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end blog -->
      <!--  contact -->
      <div class="contact">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="titlepage">
                     <h2>Contact Us</h2>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-md-6">
                  <form id="request" class="main_form">
                     <div class="row">
                        <div class="col-md-12 ">
                           <input class="contactus" placeholder="Name" type="type" name="Name"> 
                        </div>
                        <div class="col-md-12">
                           <input class="contactus" placeholder="Email" type="type" name="Email"> 
                        </div>
                        <div class="col-md-12">
                           <input class="contactus" placeholder="Phone Number" type="type" name="Phone Number">                          
                        </div>
                        <div class="col-md-12">
                           <textarea class="textarea" placeholder="Message" type="type" Message="Name">Message</textarea>
                        </div>
                        <div class="col-md-12">
                           <button class="send_btn">Send</button>
                        </div>
                     </div>
                  </form>
               </div>
               <div class="col-md-6">
                  <div class="map_main">
                     <div class="map-responsive">
                        <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA0s1a7phLN0iaD6-UE7m4qP-z21pH0eSc&amp;q=Eiffel+Tower+Paris+France" width="600" height="400" frameborder="0" style="border:0; width: 100%;" allowfullscreen=""></iframe>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- end contact -->
{%endblock%}

templates/login.html
{%extends "base.html"%}
{%block content%}
<section class="vh-100 bg-image"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp'); margin: 10px 0;">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Đăng nhập</h2>

              <form action="." method="POST" class="mx-1 mx-md-4">
                {%csrf_token%}
                {% for key,value in form.errol.items %}
                    {{value}}
                {% endfor %}
                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example1cg">User Name</label>
                  {{form.username}}
                </div>

                <div class="form-outline mb-4">
                  <label class="form-label" for="form3Example4cg">Password</label>
                  {{form.password}}
                </div>
                <input type="hidden" name="next" value="/">
                <div class="d-flex justify-content-center">
                  <input type="submit" class="btn btn-success btn-block btn-lg gradient-custom-4 text-body" value="Đăng nhập">
                </div>

                <p class="text-center text-muted mt-5 mb-0">Bạn chưa có tài khoản? <a href="{% url 'register' %}"
                    class="fw-bold text-body"><u>Đăng ký tại đây</u></a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{%endblock%}

templates/phongdetail.html
{%extends "base.html"%}
{%block content%}
<div class="back_re">
    <div class="container">
       <div class="row">
          <div class="col-md-12">
             <div class="title">
               <h2>Chi tiết phòng</h2>
             </div>
          </div>
       </div>
    </div>
</div>
<section class="py-5">
   <div class="container px-4 px-lg-5 my-5">
      <div class="row gx-4 gx-lg-5 align-items-center">
         <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="../static/images/{{fm.Anhphong}}" alt="..." /></div>
         <div class="col-md-6">
            <h1 class="display-5 fw-bolder">{{fm.Loaiphong}}</h1>
            <h3 class="display-5 fw-bolder">{{fm.Sogiuong}}</h3>
            <div class="fs-5 mb-5">
               <span class="text-decoration-line-through"></span>
               <span>{{fm.Giaphong}}VNĐ/Đêm</span>
            </div>
            <p class="lead">{{fm.describe}}</p>
            <div class="d-flex">
               <a href="{% url 'datphong'%}?id={{fm.Maphong}}">
                  <div class="btn btn-outline-dark flex-shrink-0" value="">
                     Đặt phòng
                  </div>
               </a> 
            </div>
         </div>
      </div>
   </div>
</section>
{%endblock%}

templates/suatt.html
{%extends "base.html"%}
{%block content%}
    <div class="back_re">
        <div class="container">
           <div class="row">
              <div class="col-md-12">
                 <div class="title">
                   <h2>Sửa Thông Tin Khách Hàng - {{ khach_hang.Cccd }}</h2>
                 </div>
              </div>
           </div>
        </div>
    </div>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Lưu Thay Đổi</button>
    </form>
{%endblock%}